[jobs.check]
command = ["cargo", "check", "--workspace", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--workspace",
  "--all-targets",
  "--color",
  "always",
  "--",
  "-D",
  "warnings",
]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--workspace", "--color", "always"]
need_stdout = true

[jobs.run]
command = ["cargo", "run", "-p", "tuigotchi-tui", "--color", "always"]
need_stdout = true
allow_warnings = true
background = true

[keybindings]
c = "job:check"
l = "job:clippy"
t = "job:test"
r = "job:run"
